name: Build and Publish Release

on:
  push:
  #   branches:
  #     - "main"
  # pull_request:
  #   branches: 
  #     - "*"
  #     - "!main"

env: {}

jobs:
  setup-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: |
          TASKS=$(echo $(cat .github/workflows/go-matrix.json) | sed 's/ //g' )
          echo 'matrix=$TASKS' >> $GITHUB_ENV

  build-server:
    name: Build Server
    runs-on: ubuntu-latest
    needs: [setup-matrix]
    strategy:
      matrix: ${{fromJSON(env.matrix)}}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Build server
        run: cd ./server; GOOS="${{ matrix.target.os }}" GOARCH="${{ matrix.target.arch }}" go build -o ../dist/server/web-scanner-${{ matrix.target.os }}-${{ matrix.target.arch }} .
      - name: Copy server default settings file
        run: cp ./server/settings.toml ./dist/
     
  build-client:
    name: Build client
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Setup Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: 'npm'
          cache-dependency-path: "./client/package-lock.json"
      - name: Install dependencies
        run: cd ./client; npm install
      - name: Build client
        run: cd ./client; npm run build-actions
  
  zip-file:
    name: Zip files
    runs-on: ubuntu-latest
    needs: [setup-matrix, build-server, build-client]
    strategy:
      matrix: ${{fromJSON(env.matrix)}}
    steps:
      - run: |
          # cd dist
          OUTPATH=./dist/web-scanner-${{ matrix.target.os }}-${{ matrix.target.arch }}/web-scanner
          mkdir -p $OUTPATH
          cp -r ./client $OUTPATH
          cp settings.toml $OUTPATH
          cp ./dist/server/web-scanner-${{ matrix.target.os }}-${{ matrix.target.arch }} $OUTPATH
          cd ./dist/web-scanner-${{ matrix.target.os }}-${{ matrix.target.arch }}
          zip -r ../../web-scanner-${{ matrix.target.os }}-${{ matrix.target.arch }}.zip ./client ./settings.toml ./web-scanner-${{ matrix.target.os }}-${{ matrix.target.arch }}
  
  # release:
  #   name: release
  #   runs-on: ubuntu-latest
  #   needs: zip-file
  #   steps:
  #     - uses: "marvinpinto/action-automatic-releases@latest"
  #       with:
  #         repo_token: "${{ secrets.GITHUB_TOKEN }}"
  #         automatic_release_tag: "latest"
  #         prerelease: true
  #         title: "Development Build"
  #         files: |
  #           ./dist/web-scanner-*.zip
      
      